export const Navigation_Routes = {
  dashboard: "/",
  organization: "/organization",
  unit: "/unit",
  branch: "/branch",
  committee: "/committee",
  designation: "/designation",
  deduction: "/deduction",
  distance: "/distance",
  user: "/user",
  committee_type: "/committee-type",
  meeting_type: "/meeting-type",
  fiscal_year: "/fiscal-year",
  allowance_type: "/allowance-type",
  document_type: "/document-type",
  setup_allowance: "/setup-allowance",
  telephone_allowance: "/telephone-allowance",
};
